/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.uniregensburg;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException, InterruptedException {
        System.out.println(new App().getGreeting());
        String query = "(Online OR Internet OR Web)";
        ApiClient apiClient = new ApiClient();
        apiClient.performRequest(query);
    }
}
